version: '3'

services:
  frontend:
    container_name: "fr"
    build: front
    ports:
      - 3000:3000
    networks:
      app:
        ipv4_address: "10.10.10.2"
    volumes:
      - ./front/src:/code/src:ro
  backend:
    build: back
    ports:
      - 3001:3001
    networks:
      app:
        ipv4_address: 10.10.10.3
    volumes:
      - ./back/src:/code/src
  database:
    image: postgres:14
    networks:
      app:
        ipv4_address: 10.10.10.4
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
    volumes: 
      - appdb:/var/lib/postgresql/data

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.10.0/24"

volumes:
  appdb:


